### ISSUE TITLE
bower.json 也应该使用 devDependencies

### ISSUE THREAD

**Issue by ifduyue** [Jisuanke/plugin_builder#5]

**Comment by Foolyou** [comment]
对。

**Comment by Foolyou** [comment]
已更新V1.0.8。

**Comment by Foolyou** [comment]
@ifduyue 
当时写到Dependencies是因为CodeMirror会被Jisuanke2里的codemirror:mode任务用到。这里请问一下杜神，现在的CodeMirror是将用到的mode（clike, python, ruby, html等）打包到codemirror.js中的，还有没有必要留着codemirror:mode这个任务？

' codemirror:mode任务将所有的mode文件放到public/assets/codemirror/mode下，以供动态加载使用。

**Comment by ifduyue** [comment]
可以去掉了
